# Configuración del botón de patrocinio (Sponsor button)
# Este archivo habilita el botón de patrocinio en el repositorio

github: caroacostatovany # GitHub Sponsors

# Otras plataformas de financiamiento (descomenta si las usas):
# patreon: # Tu usuario de Patreon
# open_collective: # Tu organización de Open Collective
# ko_fi: # Tu usuario de Ko-fi
# liberapay: # Tu usuario de Liberapay
# issuehunt: # Tu usuario de IssueHunt
# otechie: # Tu usuario de Otechie
# lfx_crowdfunding: # Tu proyecto de LFX Crowdfunding
# custom: # URLs personalizadas (ejemplo: ["https://mi-sitio.com/donar", "https://otro-sitio.com/patrocinar"]

# Más información: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
